[package]
name = "platinum"
version = "0.1.0"
authors = ["John Doneth <Doneth7@gmail.com>", "Jarred Parr <jpar721@gmail.com>"]

[dependencies]


[target.'cfg(windows)'.dependencies]
winapi = "*"
user32-sys = "*"
